### ISSUE TITLE
加载插件时抛出 java.lang.LinkageError 错误

### ISSUE THREAD

**Issue by shinyashen** [xszqxszq/maimai-bot#10]
相关日志：
```
2022-11-14 22:01:26 I/MaimaiBot: 正在生成歌曲封面缓存图……
2022-11-14 22:01:30 I/MaimaiBot: 正在生成定数表……
2022-11-14 22:01:52 I/MaimaiBot: 成功载入所有图片。
2022-11-14 22:01:52 E/MaimaiBot: Exception in coroutine Plugin xyz.xszq.maimai-bot of MaimaiBot
java.lang.LinkageError: loader constraint violation: when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' the class loader 'maimai-bot-1.3.2.mirai.jar' @79d82f66 of the current class, org/slf4j/LoggerFactory, and the class loader 'onebot-mirai-0.3.4-all.jar' @35c4e864 for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature (org.slf4j.LoggerFactory is in unnamed module of loader 'maimai-bot-1.3.2.mirai.jar' @79d82f66, parent loader 'global-shared' @4b65d9f4; org.slf4j.impl.StaticLoggerBinder is in unnamed module of loader 'onebot-mirai-0.3.4-all.jar' @35c4e864, parent loader 'global-shared' @4b65d9f4)
        at maimai-bot-1.3.2.mirai.jar//org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:423)
        at maimai-bot-1.3.2.mirai.jar//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at maimai-bot-1.3.2.mirai.jar//mu.KotlinLogging.logger(KotlinLogging.kt:32)
        at maimai-bot-1.3.2.mirai.jar//com.github.doyaaaaaken.kotlincsv.client.CsvFileReader.<init>(CsvFileReader.kt:22)
        at maimai-bot-1.3.2.mirai.jar//com.github.doyaaaaaken.kotlincsv.client.CsvReader.openAsync(CsvReader.kt:182)
        at maimai-bot-1.3.2.mirai.jar//com.github.doyaaaaaken.kotlincsv.client.CsvReader.openAsync(CsvReader.kt:143)
        at maimai-bot-1.3.2.mirai.jar//xyz.xszq.MaimaiBot.reloadAliases(MaimaiBot.kt:308)
        at maimai-bot-1.3.2.mirai.jar//xyz.xszq.MaimaiBot.reload(MaimaiBot.kt:305)
        at maimai-bot-1.3.2.mirai.jar//xyz.xszq.MaimaiBot.access$reload(MaimaiBot.kt:75)
        at maimai-bot-1.3.2.mirai.jar//xyz.xszq.MaimaiBot$reload$1.invokeSuspend(MaimaiBot.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

此外，在加载 **mcmotd-1.1.8.mirai.jar** 插件时，也会抛出该错误，相关日志如下：
```
2022-11-14 21:52:42 I/MaimaiBot: 正在生成歌曲封面缓存图……
2022-11-14 21:52:50 I/MaimaiBot: 正在生成定数表……
2022-11-14 21:53:12 I/MaimaiBot: 成功载入所有图片。
2022-11-14 21:53:12 E/MaimaiBot: Exception in coroutine Plugin xyz.xszq.maimai-bot of MaimaiBot
java.lang.LinkageError: loader constraint violation: when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' the class loader 'maimai-bot-1.3.2.mirai.jar' @79d82f66 of the current class, org/slf4j/LoggerFactory, and the class loader 'mcmotd-1.1.8.mirai.jar' @1e977098 for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature (org.slf4j.LoggerFactory is in unnamed module of loader 'maimai-bot-1.3.2.mirai.jar' @79d82f66, parent loader 'global-shared' @4b65d9f4; org.slf4j.impl.StaticLoggerBinder is in unnamed module of loader 'mcmotd-1.1.8.mirai.jar' @1e977098, parent loader 'global-shared' @4b65d9f4)
        at maimai-bot-1.3.2.mirai.jar//org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:423)
        at maimai-bot-1.3.2.mirai.jar//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at maimai-bot-1.3.2.mirai.jar//mu.KotlinLogging.logger(KotlinLogging.kt:32)
        at maimai-bot-1.3.2.mirai.jar//com.github.doyaaaaaken.kotlincsv.client.CsvFileReader.<init>(CsvFileReader.kt:22)
        at maimai-bot-1.3.2.mirai.jar//com.github.doyaaaaaken.kotlincsv.client.CsvReader.openAsync(CsvReader.kt:182)
        at maimai-bot-1.3.2.mirai.jar//com.github.doyaaaaaken.kotlincsv.client.CsvReader.openAsync(CsvReader.kt:143)
        at maimai-bot-1.3.2.mirai.jar//xyz.xszq.MaimaiBot.reloadAliases(MaimaiBot.kt:308)
        at maimai-bot-1.3.2.mirai.jar//xyz.xszq.MaimaiBot.reload(MaimaiBot.kt:305)
        at maimai-bot-1.3.2.mirai.jar//xyz.xszq.MaimaiBot.access$reload(MaimaiBot.kt:75)
        at maimai-bot-1.3.2.mirai.jar//xyz.xszq.MaimaiBot$reload$1.invokeSuspend(MaimaiBot.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by xszqxszq** [comment]
如果其他插件也报可能是mirai的问题，现在的打包模式不会影响其他插件的依赖

**Comment by xszqxszq** [comment]
新版是否还有这个问题

**Comment by luocixi** [comment]
出现了这个问题
