### ISSUE TITLE
user note：不影响运行的报错

### ISSUE THREAD

**Issue by MC57348** [xszqxszq/maimai-bot#12]
在运行过程中会出现如下警告，但是不影响运行，担心未来是否会出现问题
`2022-12-01 01:00:51 W/stderr: Exception in thread "DefaultDispatcher-worker-10" java.lang.NoSuchMethodError: 'net.mamoe.mirai.data.GroupHonorType net.mamoe.mirai.event.events.MemberHonorChangeEvent$Achieve.getHonorType()'
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.EventKt.convertBotEvent(event.kt:119)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.ConvertorKt.toDTO(convertor.kt:44)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.http.HttpAdapter.onReceiveBotEvent(HttpAdapter.kt:42)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.context.MahContext$handleBotEvent$1$1.invokeSuspend(MahContext.kt:116)
2022-12-01 01:00:51 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-12-01 01:00:51 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@62bf69f, Dispatchers.Default]
2022-12-01 01:00:51 W/stderr: Exception in thread "DefaultDispatcher-worker-15" Exception in thread "DefaultDispatcher-worker-1" java.lang.NoSuchMethodError: 'net.mamoe.mirai.data.GroupHonorType net.mamoe.mirai.event.events.MemberHonorChangeEvent$Achieve.getHonorType()'
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.EventKt.convertBotEvent(event.kt:119)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.ConvertorKt.toDTO(convertor.kt:44)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.http.HttpAdapter.onReceiveBotEvent(HttpAdapter.kt:42)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.context.MahContext$handleBotEvent$1$1.invokeSuspend(MahContext.kt:116)
2022-12-01 01:00:51 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-12-01 01:00:51 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@580feb80, Dispatchers.Default]
2022-12-01 01:00:51 W/stderr: Exception in thread "DefaultDispatcher-worker-7" java.lang.NoSuchMethodError: 'net.mamoe.mirai.data.GroupHonorType net.mamoe.mirai.event.events.MemberHonorChangeEvent$Achieve.getHonorType()'
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.EventKt.convertBotEvent(event.kt:119)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.ConvertorKt.toDTO(convertor.kt:44)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.http.HttpAdapter.onReceiveBotEvent(HttpAdapter.kt:42)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.context.MahContext$handleBotEvent$1$1.invokeSuspend(MahContext.kt:116)
2022-12-01 01:00:51 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-12-01 01:00:51 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6bcab241, Dispatchers.Default]
2022-12-01 01:00:51 W/stderr: Exception in thread "DefaultDispatcher-worker-4" java.lang.NoSuchMethodError: 'net.mamoe.mirai.data.GroupHonorType net.mamoe.mirai.event.events.MemberHonorChangeEvent$Achieve.getHonorType()'
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.EventKt.convertBotEvent(event.kt:119)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.ConvertorKt.toDTO(convertor.kt:44)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.http.HttpAdapter.onReceiveBotEvent(HttpAdapter.kt:42)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.context.MahContext$handleBotEvent$1$1.invokeSuspend(MahContext.kt:116)
2022-12-01 01:00:51 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-12-01 01:00:51 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4674fd33, Dispatchers.Default]
2022-12-01 01:00:51 W/stderr: java.lang.NoSuchMethodError: 'net.mamoe.mirai.data.GroupHonorType net.mamoe.mirai.event.events.MemberHonorChangeEvent$Achieve.getHonorType()'
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.EventKt.convertBotEvent(event.kt:119)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.internal.convertor.ConvertorKt.toDTO(convertor.kt:44)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.adapter.http.HttpAdapter.onReceiveBotEvent(HttpAdapter.kt:42)
2022-12-01 01:00:51 W/stderr:   at mirai-api-http-2.6.2.jar//net.mamoe.mirai.api.http.context.MahContext$handleBotEvent$1$1.invokeSuspend(MahContext.kt:116)
2022-12-01 01:00:51 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2022-12-01 01:00:51 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-12-01 01:00:51 W/stderr:   Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@506c869e, Dispatchers.Default]`

**Comment by MC57348** [comment]
2022-11-30 15:11:19 I/main: Backend: version 2.13.0, built on 2022-11-01 10:47:11.
2022-11-30 15:11:19 I/main: Frontend Terminal: version 2.13.0, provided by Mamoe Technologies
2022-11-30 15:11:22 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2022-11-30 15:11:20 I/plugin: Successfully loaded plugin MaimaiBot v1.3.0（在控制台里依旧显示为1.3.0，但实际版本已为1.3.
3）

**Comment by xszqxszq** [comment]
这个是mirai的问题吧，我这边没有调用getHonorType

**Comment by MC57348** [comment]
感觉看起来像是分组问题？

**Comment by xszqxszq** [comment]
> 感觉看起来像是分组问题？

群荣誉的问题，可能是你其他插件用的mirai版本和实际的运行版本不一样
