### ISSUE TITLE
使用 classical 时，出现错误；求助如何更新查询页面 UI

### ISSUE THREAD

**Issue by theLucius7** [xszqxszq/maimai-bot#17]
```
 E/MaimaiBot: Exception in coroutine Plugin xyz.xszq.maimai-bot of MaimaiBot
kotlinx.serialization.MissingFieldException: Fields [dsList, info] are required for type with serial name 'xyz.xszq.MaimaiPicTheme', but they were missing
        at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
        at maimai-bot-1.3.6.mirai.jar//xyz.xszq.MaimaiPicTheme.<init>(DrawImage.kt:513)
        at maimai-bot-1.3.6.mirai.jar//xyz.xszq.MaimaiPicTheme$$serializer.deserialize(DrawImage.kt:513)
        at maimai-bot-1.3.6.mirai.jar//xyz.xszq.MaimaiPicTheme$$serializer.deserialize(DrawImage.kt:513)
        at net.mamoe.yamlkt.Yaml.decodeFromString(Yaml.kt:162)
        at maimai-bot-1.3.6.mirai.jar//xyz.xszq.MaimaiBot.reload(MaimaiBot.kt:1154)
        at maimai-bot-1.3.6.mirai.jar//xyz.xszq.MaimaiBot.access$reload(MaimaiBot.kt:79)
        at maimai-bot-1.3.6.mirai.jar//xyz.xszq.MaimaiBot$reload$1.invokeSuspend(MaimaiBot.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at maimai-bot-1.3.6.mirai.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at maimai-bot-1.3.6.mirai.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at maimai-bot-1.3.6.mirai.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at maimai-bot-1.3.6.mirai.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at maimai-bot-1.3.6.mirai.jar//io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at maimai-bot-1.3.6.mirai.jar//io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at maimai-bot-1.3.6.mirai.jar//io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at maimai-bot-1.3.6.mirai.jar//io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

查询页面 UI 如图：（感觉需要更新）
![QQ图片20230430100829](https://user-images.githubusercontent.com/59860644/235332675-b8879020-eb5e-40a1-a508-09d57e194252.png)

**Comment by xszqxszq** [comment]
收到

**Comment by xszqxszq** [comment]
临时解决方案是把portrait主题里的的dsList和info两项复制过来，classical主题的真没做（
