### ISSUE TITLE
bot插件运行一段时候后报错

### ISSUE THREAD

**Issue by AKAPotato** [xszqxszq/maimai-bot#31]
2023-10-10 15:11:29 V/Bot.1919755643: Group(735538390) <- [mirai:quote:[mirai:source:ids=[82488], internalIds=[470522755], from group 2098714594 to 735538390 at 1696921887], content=info 清华][mirai:image:{6424F48F-A6B9-EA03-D783-C42BF3783089}.png, width=1080, height=960, size=527569, type=PNG, isEmoji=false]
2023-10-10 15:11:30 V/Bot.1919755643: [青陨的超级面包工坊(849985512)] 星穹铁道高手(1377369041) -> [mirai:image:{0721174B-B1BC-27F5-50C8-3409966F7FD0}.jpg, width=606, height=970, size=65480, type=JPG, isEmoji=true]
2023-10-10 15:11:32 V/Bot.1919755643: [广东- DCY 发癫总部(928032323)] 亦 ⁧     ~giao(271272008) -> b50
2023-10-10 15:11:33 V/Bot.1919755643: Group(928032323) <- [mirai:quote:[mirai:source:ids=[608], internalIds=[1165801476], from group 271272008 to 928032323 at 1696921892], content=b50]正在生成中……
2023-10-10 15:11:35 V/Bot.1919755643: [雀尼玛魂群(735538390)] 阴暗的蠕动(2098714594) -> [mirai:image:{DEDC6D68-82B0-9E3C-DF9D-E92B87431C0D}.png, width=1080, height=1116, size=53959, type=JPG, isEmoji=true]
2023-10-10 15:11:37 V/Bot.1919755643: [雀尼玛魂群(735538390)] BlackY vs. WAiKURO(2353595896) -> oboro没古神高
2023-10-10 15:11:37 V/Bot.1919755643: [雀尼玛魂群(735538390)] 棉兔子(384442008) -> 已收到
2023-10-10 15:11:38 V/Bot.1919755643: [雀尼玛魂群(735538390)] BlackY vs. WAiKURO(2353595896) -> 笑了
2023-10-10 15:11:38 V/Bot.1919755643: [饭饭第三心窝窝(334113448)] 金步戈(610611251) -> [mirai:quote:[mirai:source:ids=[50803], internalIds=[213743232], from 3211617364 to 334113448 at 1696921729], content=<not yet initialized>][mirai:at:3211617364] ？
2023-10-10 15:11:41 V/Bot.1919755643: [雀尼玛魂群(735538390)] 棉兔子(384442008) -> 在观摩
2023-10-10 15:11:43 V/Bot.1919755643: [饭饭第三心窝窝(334113448)] 金步戈(610611251) -> [mirai:image:{0B158273-A9D8-89C8-5311-CA57A51AD8B1}.jpg, width=300, height=294, size=13469, type=JPG, isEmoji=true]
2023-10-10 15:11:44 V/Bot.1919755643: [雀尼玛魂群(735538390)] 棉兔子(384442008) -> 美妙的玉米棒
2023-10-10 15:11:48 V/Bot.1919755643: [放学后音趴会社(852257356)] 乌有的乌有(2905706142) -> OK
2023-10-10 15:11:52 V/Bot.1919755643: [珠海舞萌生活群(437189122)] 只会红谱，图个喜庆(3168737024) -> info 茄子
2023-10-10 15:11:53 E/MaimaiBot: Exception in coroutine Plugin xyz.xszq.maimai-bot of MaimaiBot
java.lang.IllegalStateException: running
	at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.AbstractEmulator.emulate(AbstractEmulator.java:352)
	at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.thread.Function64.run(Function64.java:39)
	at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.thread.MainTask.dispatch(MainTask.java:19)
	at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.thread.UniThreadDispatcher.run(UniThreadDispatcher.java:175)
	at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.thread.UniThreadDispatcher.runMainForResult(UniThreadDispatcher.java:99)
	at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.AbstractEmulator.runMainForResult(AbstractEmulator.java:340)
	at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.arm.AbstractARM64Emulator.eFunc(AbstractARM64Emulator.java:262)
	at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.Module.emulateFunction(Module.java:163)
	at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.linux.android.dvm.DvmObject.callJniMethod(DvmObject.java:135)
	at qsign-1.1.0-beta.mirai2.jar//com.github.unidbg.linux.android.dvm.DvmObject.callJniMethodObject(DvmObject.java:93)
	at qsign-1.1.0-beta.mirai2.jar//com.tencent.mobileqq.qsec.qsecurity.QSec.getEst(QSec.kt:16)
	at qsign-1.1.0-beta.mirai2.jar//moe.fuqiuluo.api.UnidbgFetchQSign.sign(UnidbgFetchQSign.kt:172)
	at qsign-1.1.0-beta.mirai2.jar//moe.fuqiuluo.api.UnidbgFetchQSign.sign$default(UnidbgFetchQSign.kt:146)
	at qsign-1.1.0-beta.mirai2.jar//top.mrxiaom.qsign.QSignService$qSecurityGetSign$data$1.invokeSuspend(QSignService.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at qsign-1.1.0-beta.mirai2.jar//top.mrxiaom.qsign.QSignService.qSecurityGetSign(QSignService.kt:98)
	at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.buildRawUniPacket(OutgoingPacket.kt:139)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbSendMsg.createToGroupImpl$mirai_core(MessageSvc.PbSendMsg.kt:744)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvc_PbSendMsgKt.createToGroup(MessageSvc.PbSendMsg.kt:585)
	at net.mamoe.mirai.internal.message.protocol.outgoing.GroupMessageProtocolStrategy.createPacketsForGeneralMessage$suspendImpl(MessageProtocolStrategy.kt:150)
	at net.mamoe.mirai.internal.message.protocol.outgoing.GroupMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt)
	at net.mamoe.mirai.internal.message.protocol.outgoing.GroupMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt:139)
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.process(GeneralMessageSenderProtocol.kt:66)
	at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:26)
	at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:20)
	at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:287)
	at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)
	at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoingImpl(MessageProtocolFacade.kt:361)
	at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoing(MessageProtocolFacade.kt:345)
	at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.preprocessAndSendOutgoing(MessageProtocolFacade.kt)
	at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:263)
	at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage$suspendImpl(GroupImpl.kt:221)
	at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage(GroupImpl.kt)
	at maimai-bot-1.3.8.mirai.jar//xyz.xszq.UtilsKt.quoteReply(Utils.kt:85)
	at maimai-bot-1.3.8.mirai.jar//xyz.xszq.MaimaiBot$generateMusicInfo$2.invokeSuspend(MaimaiBot.kt:1163)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by xszqxszq** [comment]
这个可能是签名服务那边的错误，再看看能不能找到复现条件
